import './js/refs';
import './js/searchByKeyWord';
import './js/trailer';
import './js/modal-movie';
import './js/markupModal';
import './js/apiService';
import './js/renderingGalleryMarkup';
import './js/team-modal';
import './js/modal-btns-library';